apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hello-server
  name: hello-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-server
    spec:
      containers:
      - image: paulc4/hello-server:latest
        command: ["java"]
        args: ["-jar", "/app.jar"]
        name: hello-server
        ports:
        - containerPort: 8080
